package com.redfinger.manager.common.gather.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.redfinger.manager.common.gather.domain.RfGatherExpand;
import com.redfinger.manager.common.gather.domain.RfGatherExpandExample;

public interface RfGatherExpandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int countByExample(RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int deleteByExample(RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int deleteByPrimaryKey(Integer expandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int insert(RfGatherExpand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int insertSelective(RfGatherExpand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    List<RfGatherExpand> selectByExample(RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    RfGatherExpand selectByPrimaryKey(Integer expandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") RfGatherExpand record, @Param("example") RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int updateByExample(@Param("record") RfGatherExpand record, @Param("example") RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int updateByPrimaryKeySelective(RfGatherExpand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int updateByPrimaryKey(RfGatherExpand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    RfGatherExpand selectOneByExample(RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    List<RfGatherExpand> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    RfGatherExpand selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int insertBatch(List<RfGatherExpand> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int updateByExampleSelectiveSync(@Param("record") RfGatherExpand record, @Param("example") RfGatherExpandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    int updateByPrimaryKeySelectiveSync(RfGatherExpand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_gather_expand
     *
     * @mbggenerated Thu Jul 27 10:17:55 CST 2017
     */
    RfGatherExpand selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("expandId") Integer expandId);
}