package com.redfinger.manager.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RfFaultHandleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public RfFaultHandleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFaultHandleIdIsNull() {
			addCriterion("fault_handle_id is null");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdIsNotNull() {
			addCriterion("fault_handle_id is not null");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdEqualTo(Integer value) {
			addCriterion("fault_handle_id =", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdNotEqualTo(Integer value) {
			addCriterion("fault_handle_id <>", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdGreaterThan(Integer value) {
			addCriterion("fault_handle_id >", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("fault_handle_id >=", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdLessThan(Integer value) {
			addCriterion("fault_handle_id <", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdLessThanOrEqualTo(Integer value) {
			addCriterion("fault_handle_id <=", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdIn(List<Integer> values) {
			addCriterion("fault_handle_id in", values, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdNotIn(List<Integer> values) {
			addCriterion("fault_handle_id not in", values, "faultHandleId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andFaultHandleIdBetween(Integer value1, Integer value2) {
			addCriterion("fault_handle_id between", value1, value2, "faultHandleId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andFaultHandleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("fault_handle_id not between", value1, value2, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdIsNull() {
			addCriterion("admin_user_id is null");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdIsNotNull() {
			addCriterion("admin_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdEqualTo(String value) {
			addCriterion("admin_user_id =", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdNotEqualTo(String value) {
			addCriterion("admin_user_id <>", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdGreaterThan(String value) {
			addCriterion("admin_user_id >", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("admin_user_id >=", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdLessThan(String value) {
			addCriterion("admin_user_id <", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdLessThanOrEqualTo(String value) {
			addCriterion("admin_user_id <=", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdLike(String value) {
			addCriterion("admin_user_id like", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdNotLike(String value) {
			addCriterion("admin_user_id not like", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdIn(List<String> values) {
			addCriterion("admin_user_id in", values, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdNotIn(List<String> values) {
			addCriterion("admin_user_id not in", values, "adminUserId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andAdminUserIdBetween(String value1, String value2) {
			addCriterion("admin_user_id between", value1, value2, "adminUserId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andAdminUserIdNotBetween(String value1, String value2) {
			addCriterion("admin_user_id not between", value1, value2, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdIsNull() {
			addCriterion("fault_feedback_id is null");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdIsNotNull() {
			addCriterion("fault_feedback_id is not null");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdEqualTo(Integer value) {
			addCriterion("fault_feedback_id =", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdNotEqualTo(Integer value) {
			addCriterion("fault_feedback_id <>", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdGreaterThan(Integer value) {
			addCriterion("fault_feedback_id >", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("fault_feedback_id >=", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdLessThan(Integer value) {
			addCriterion("fault_feedback_id <", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdLessThanOrEqualTo(Integer value) {
			addCriterion("fault_feedback_id <=", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdIn(List<Integer> values) {
			addCriterion("fault_feedback_id in", values, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdNotIn(List<Integer> values) {
			addCriterion("fault_feedback_id not in", values, "faultFeedbackId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andFaultFeedbackIdBetween(Integer value1, Integer value2) {
			addCriterion("fault_feedback_id between", value1, value2, "faultFeedbackId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andFaultFeedbackIdNotBetween(Integer value1, Integer value2) {
			addCriterion("fault_feedback_id not between", value1, value2, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveIsNull() {
			addCriterion("is_solve is null");
			return (Criteria) this;
		}

		public Criteria andIsSolveIsNotNull() {
			addCriterion("is_solve is not null");
			return (Criteria) this;
		}

		public Criteria andIsSolveEqualTo(String value) {
			addCriterion("is_solve =", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveNotEqualTo(String value) {
			addCriterion("is_solve <>", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveGreaterThan(String value) {
			addCriterion("is_solve >", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveGreaterThanOrEqualTo(String value) {
			addCriterion("is_solve >=", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveLessThan(String value) {
			addCriterion("is_solve <", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveLessThanOrEqualTo(String value) {
			addCriterion("is_solve <=", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveLike(String value) {
			addCriterion("is_solve like", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveNotLike(String value) {
			addCriterion("is_solve not like", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveIn(List<String> values) {
			addCriterion("is_solve in", values, "isSolve");
			return (Criteria) this;
		}

		public Criteria andIsSolveNotIn(List<String> values) {
			addCriterion("is_solve not in", values, "isSolve");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andIsSolveBetween(String value1, String value2) {
			addCriterion("is_solve between", value1, value2, "isSolve");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andIsSolveNotBetween(String value1, String value2) {
			addCriterion("is_solve not between", value1, value2, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterIsNull() {
			addCriterion("creater is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIsNotNull() {
			addCriterion("creater is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterEqualTo(String value) {
			addCriterion("creater =", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotEqualTo(String value) {
			addCriterion("creater <>", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThan(String value) {
			addCriterion("creater >", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanOrEqualTo(String value) {
			addCriterion("creater >=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThan(String value) {
			addCriterion("creater <", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanOrEqualTo(String value) {
			addCriterion("creater <=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLike(String value) {
			addCriterion("creater like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotLike(String value) {
			addCriterion("creater not like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterIn(List<String> values) {
			addCriterion("creater in", values, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotIn(List<String> values) {
			addCriterion("creater not in", values, "creater");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreaterBetween(String value1, String value2) {
			addCriterion("creater between", value1, value2, "creater");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreaterNotBetween(String value1, String value2) {
			addCriterion("creater not between", value1, value2, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("modifier is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("modifier is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("modifier like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("modifier not like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<String> values) {
			addCriterion("modifier in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<String> values) {
			addCriterion("modifier not in", values, "modifier");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifierBetween(String value1, String value2) {
			addCriterion("modifier between", value1, value2, "modifier");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("modifier not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderIsNull() {
			addCriterion("reorder is null");
			return (Criteria) this;
		}

		public Criteria andReorderIsNotNull() {
			addCriterion("reorder is not null");
			return (Criteria) this;
		}

		public Criteria andReorderEqualTo(Integer value) {
			addCriterion("reorder =", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotEqualTo(Integer value) {
			addCriterion("reorder <>", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThan(Integer value) {
			addCriterion("reorder >", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanOrEqualTo(Integer value) {
			addCriterion("reorder >=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLessThan(Integer value) {
			addCriterion("reorder <", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanOrEqualTo(Integer value) {
			addCriterion("reorder <=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderIn(List<Integer> values) {
			addCriterion("reorder in", values, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotIn(List<Integer> values) {
			addCriterion("reorder not in", values, "reorder");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andReorderBetween(Integer value1, Integer value2) {
			addCriterion("reorder between", value1, value2, "reorder");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andReorderNotBetween(Integer value1, Integer value2) {
			addCriterion("reorder not between", value1, value2, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIsNull() {
			addCriterion("enable_status is null");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIsNotNull() {
			addCriterion("enable_status is not null");
			return (Criteria) this;
		}

		public Criteria andEnableStatusEqualTo(String value) {
			addCriterion("enable_status =", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotEqualTo(String value) {
			addCriterion("enable_status <>", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThan(String value) {
			addCriterion("enable_status >", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanOrEqualTo(String value) {
			addCriterion("enable_status >=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThan(String value) {
			addCriterion("enable_status <", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanOrEqualTo(String value) {
			addCriterion("enable_status <=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLike(String value) {
			addCriterion("enable_status like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotLike(String value) {
			addCriterion("enable_status not like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIn(List<String> values) {
			addCriterion("enable_status in", values, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotIn(List<String> values) {
			addCriterion("enable_status not in", values, "enableStatus");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andEnableStatusBetween(String value1, String value2) {
			addCriterion("enable_status between", value1, value2, "enableStatus");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andEnableStatusNotBetween(String value1, String value2) {
			addCriterion("enable_status not between", value1, value2, "enableStatus");
			return (Criteria) this;
		}

		protected void addCriterionIgnoreNull(String condition, Object value, String property) {
			if (value != null) {
				if (value instanceof String) {
					if (((String) value).length() > 0) {
						criteria.add(new Criterion(condition, value));
					}
				} else if (value instanceof List<?>) {
					if (((List<?>) value).size() > 0) {
						criteria.add(new Criterion(condition, value));
					}
				} else {
					criteria.add(new Criterion(condition, value));
				}
			}
		}

		public Criteria andFaultHandleIdEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_handle_id =", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("admin_user_id =", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_feedback_id =", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("is_solve =", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater =", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder =", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status =", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_handle_id <>", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("admin_user_id <>", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_feedback_id <>", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("is_solve <>", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <>", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder <>", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <>", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_handle_id >", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("admin_user_id >", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_feedback_id >", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("is_solve >", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("creater >", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder >", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status >", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_handle_id >=", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("admin_user_id >=", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_feedback_id >=", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("is_solve >=", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater >=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder >=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status >=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_handle_id <", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("admin_user_id <", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_feedback_id <", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("is_solve <", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder <", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_handle_id <=", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("admin_user_id <=", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("fault_feedback_id <=", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("is_solve <=", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder <=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("fault_handle_id in", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("admin_user_id in", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("fault_feedback_id in", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("is_solve in", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("status in", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("creater in", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("create_time in", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("modifier in", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("modify_time in", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("reorder in", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("remark in", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("enable_status in", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andFaultHandleIdNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("fault_handle_id not in", value, "faultHandleId");
			return (Criteria) this;
		}

		public Criteria andAdminUserIdNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("admin_user_id not in", value, "adminUserId");
			return (Criteria) this;
		}

		public Criteria andFaultFeedbackIdNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("fault_feedback_id not in", value, "faultFeedbackId");
			return (Criteria) this;
		}

		public Criteria andIsSolveNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("is_solve not in", value, "isSolve");
			return (Criteria) this;
		}

		public Criteria andStatusNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("status not in", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("creater not in", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("create_time not in", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("modifier not in", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("modify_time not in", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("reorder not in", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("remark not in", value, "remark");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("enable_status not in", value, "enableStatus");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rf_fault_handle
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rf_fault_handle
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 10 14:53:35 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andAdminUserIdLikeInsensitive(String value) {
            addCriterion("upper(admin_user_id) like", value.toUpperCase(), "adminUserId");
            return this;
        }

        public Criteria andIsSolveLikeInsensitive(String value) {
            addCriterion("upper(is_solve) like", value.toUpperCase(), "isSolve");
            return this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return this;
        }

        public Criteria andCreaterLikeInsensitive(String value) {
            addCriterion("upper(creater) like", value.toUpperCase(), "creater");
            return this;
        }

        public Criteria andModifierLikeInsensitive(String value) {
            addCriterion("upper(modifier) like", value.toUpperCase(), "modifier");
            return this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return this;
        }

        public Criteria andEnableStatusLikeInsensitive(String value) {
            addCriterion("upper(enable_status) like", value.toUpperCase(), "enableStatus");
            return this;
        }
    }
}