package com.redfinger.manager.common.domain;

import com.redfinger.manager.common.base.BaseDomain;
import java.io.Serializable;
import java.util.Date;

public class RfPadGrantCode extends BaseDomain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_code_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_CODE_ID = "grant_code_id";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_code_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Integer grantCodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.user_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_USER_ID = "user_id";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.user_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_PAD_ID = "pad_id";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Integer padId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.user_pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_USER_PAD_ID = "user_pad_id";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.user_pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Integer userPadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_code
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_CODE = "grant_code";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_code
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String grantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.expire_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_EXPIRE_TIME = "expire_time";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.expire_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_control
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_CONTROL = "grant_control";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_control
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String grantControl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_watch
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_WATCH = "grant_watch";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_watch
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String grantWatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_code_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_CODE_STATUS = "grant_code_status";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_code_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String grantCodeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_TIME = "grant_time";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Date grantTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_start_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_START_TIME = "grant_start_time";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_start_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Date grantStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_end_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_GRANT_END_TIME = "grant_end_time";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.grant_end_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Date grantEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_STATUS = "status";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.enable_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_ENABLE_STATUS = "enable_status";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.enable_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.creater
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_CREATER = "creater";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.creater
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.create_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_CREATE_TIME = "create_time";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.create_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.modifier
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_MODIFIER = "modifier";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.modifier
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.modify_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_MODIFY_TIME = "modify_time";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.modify_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.reorder
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_REORDER = "reorder";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.reorder
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private Integer reorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.remark
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public static final String FD_REMARK = "remark";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rf_pad_grant_code.remark
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rf_pad_grant_code
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_code_id
     *
     * @return the value of rf_pad_grant_code.grant_code_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Integer getGrantCodeId() {
        return grantCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_code_id
     *
     * @param grantCodeId the value for rf_pad_grant_code.grant_code_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantCodeId(Integer grantCodeId) {
        this.grantCodeId = grantCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.user_id
     *
     * @return the value of rf_pad_grant_code.user_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.user_id
     *
     * @param userId the value for rf_pad_grant_code.user_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.pad_id
     *
     * @return the value of rf_pad_grant_code.pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Integer getPadId() {
        return padId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.pad_id
     *
     * @param padId the value for rf_pad_grant_code.pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setPadId(Integer padId) {
        this.padId = padId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.user_pad_id
     *
     * @return the value of rf_pad_grant_code.user_pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Integer getUserPadId() {
        return userPadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.user_pad_id
     *
     * @param userPadId the value for rf_pad_grant_code.user_pad_id
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setUserPadId(Integer userPadId) {
        this.userPadId = userPadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_code
     *
     * @return the value of rf_pad_grant_code.grant_code
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getGrantCode() {
        return grantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_code
     *
     * @param grantCode the value for rf_pad_grant_code.grant_code
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantCode(String grantCode) {
        this.grantCode = grantCode == null ? null : grantCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.expire_time
     *
     * @return the value of rf_pad_grant_code.expire_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.expire_time
     *
     * @param expireTime the value for rf_pad_grant_code.expire_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_control
     *
     * @return the value of rf_pad_grant_code.grant_control
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getGrantControl() {
        return grantControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_control
     *
     * @param grantControl the value for rf_pad_grant_code.grant_control
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantControl(String grantControl) {
        this.grantControl = grantControl == null ? null : grantControl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_watch
     *
     * @return the value of rf_pad_grant_code.grant_watch
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getGrantWatch() {
        return grantWatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_watch
     *
     * @param grantWatch the value for rf_pad_grant_code.grant_watch
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantWatch(String grantWatch) {
        this.grantWatch = grantWatch == null ? null : grantWatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_code_status
     *
     * @return the value of rf_pad_grant_code.grant_code_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getGrantCodeStatus() {
        return grantCodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_code_status
     *
     * @param grantCodeStatus the value for rf_pad_grant_code.grant_code_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantCodeStatus(String grantCodeStatus) {
        this.grantCodeStatus = grantCodeStatus == null ? null : grantCodeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_time
     *
     * @return the value of rf_pad_grant_code.grant_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Date getGrantTime() {
        return grantTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_time
     *
     * @param grantTime the value for rf_pad_grant_code.grant_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantTime(Date grantTime) {
        this.grantTime = grantTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_start_time
     *
     * @return the value of rf_pad_grant_code.grant_start_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Date getGrantStartTime() {
        return grantStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_start_time
     *
     * @param grantStartTime the value for rf_pad_grant_code.grant_start_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantStartTime(Date grantStartTime) {
        this.grantStartTime = grantStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.grant_end_time
     *
     * @return the value of rf_pad_grant_code.grant_end_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Date getGrantEndTime() {
        return grantEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.grant_end_time
     *
     * @param grantEndTime the value for rf_pad_grant_code.grant_end_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setGrantEndTime(Date grantEndTime) {
        this.grantEndTime = grantEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.status
     *
     * @return the value of rf_pad_grant_code.status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.status
     *
     * @param status the value for rf_pad_grant_code.status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.enable_status
     *
     * @return the value of rf_pad_grant_code.enable_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.enable_status
     *
     * @param enableStatus the value for rf_pad_grant_code.enable_status
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setEnableStatus(String enableStatus) {
        this.enableStatus = enableStatus == null ? null : enableStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.creater
     *
     * @return the value of rf_pad_grant_code.creater
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.creater
     *
     * @param creater the value for rf_pad_grant_code.creater
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.create_time
     *
     * @return the value of rf_pad_grant_code.create_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.create_time
     *
     * @param createTime the value for rf_pad_grant_code.create_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.modifier
     *
     * @return the value of rf_pad_grant_code.modifier
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.modifier
     *
     * @param modifier the value for rf_pad_grant_code.modifier
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.modify_time
     *
     * @return the value of rf_pad_grant_code.modify_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.modify_time
     *
     * @param modifyTime the value for rf_pad_grant_code.modify_time
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.reorder
     *
     * @return the value of rf_pad_grant_code.reorder
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public Integer getReorder() {
        return reorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.reorder
     *
     * @param reorder the value for rf_pad_grant_code.reorder
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setReorder(Integer reorder) {
        this.reorder = reorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rf_pad_grant_code.remark
     *
     * @return the value of rf_pad_grant_code.remark
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rf_pad_grant_code.remark
     *
     * @param remark the value for rf_pad_grant_code.remark
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}