package com.redfinger.manager.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RfPictureModuleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public RfPictureModuleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andModuleIdIsNull() {
			addCriterion("module_id is null");
			return (Criteria) this;
		}

		public Criteria andModuleIdIsNotNull() {
			addCriterion("module_id is not null");
			return (Criteria) this;
		}

		public Criteria andModuleIdEqualTo(Integer value) {
			addCriterion("module_id =", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotEqualTo(Integer value) {
			addCriterion("module_id <>", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThan(Integer value) {
			addCriterion("module_id >", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("module_id >=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThan(Integer value) {
			addCriterion("module_id <", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThanOrEqualTo(Integer value) {
			addCriterion("module_id <=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdIn(List<Integer> values) {
			addCriterion("module_id in", values, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotIn(List<Integer> values) {
			addCriterion("module_id not in", values, "moduleId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModuleIdBetween(Integer value1, Integer value2) {
			addCriterion("module_id between", value1, value2, "moduleId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModuleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("module_id not between", value1, value2, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeIsNull() {
			addCriterion("module_code is null");
			return (Criteria) this;
		}

		public Criteria andModuleCodeIsNotNull() {
			addCriterion("module_code is not null");
			return (Criteria) this;
		}

		public Criteria andModuleCodeEqualTo(String value) {
			addCriterion("module_code =", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeNotEqualTo(String value) {
			addCriterion("module_code <>", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeGreaterThan(String value) {
			addCriterion("module_code >", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeGreaterThanOrEqualTo(String value) {
			addCriterion("module_code >=", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeLessThan(String value) {
			addCriterion("module_code <", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeLessThanOrEqualTo(String value) {
			addCriterion("module_code <=", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeLike(String value) {
			addCriterion("module_code like", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeNotLike(String value) {
			addCriterion("module_code not like", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeIn(List<String> values) {
			addCriterion("module_code in", values, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleCodeNotIn(List<String> values) {
			addCriterion("module_code not in", values, "moduleCode");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModuleCodeBetween(String value1, String value2) {
			addCriterion("module_code between", value1, value2, "moduleCode");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModuleCodeNotBetween(String value1, String value2) {
			addCriterion("module_code not between", value1, value2, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameIsNull() {
			addCriterion("module_name is null");
			return (Criteria) this;
		}

		public Criteria andModuleNameIsNotNull() {
			addCriterion("module_name is not null");
			return (Criteria) this;
		}

		public Criteria andModuleNameEqualTo(String value) {
			addCriterion("module_name =", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameNotEqualTo(String value) {
			addCriterion("module_name <>", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameGreaterThan(String value) {
			addCriterion("module_name >", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameGreaterThanOrEqualTo(String value) {
			addCriterion("module_name >=", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameLessThan(String value) {
			addCriterion("module_name <", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameLessThanOrEqualTo(String value) {
			addCriterion("module_name <=", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameLike(String value) {
			addCriterion("module_name like", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameNotLike(String value) {
			addCriterion("module_name not like", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameIn(List<String> values) {
			addCriterion("module_name in", values, "moduleName");
			return (Criteria) this;
		}

		public Criteria andModuleNameNotIn(List<String> values) {
			addCriterion("module_name not in", values, "moduleName");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModuleNameBetween(String value1, String value2) {
			addCriterion("module_name between", value1, value2, "moduleName");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModuleNameNotBetween(String value1, String value2) {
			addCriterion("module_name not between", value1, value2, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterIsNull() {
			addCriterion("creater is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIsNotNull() {
			addCriterion("creater is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterEqualTo(String value) {
			addCriterion("creater =", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotEqualTo(String value) {
			addCriterion("creater <>", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThan(String value) {
			addCriterion("creater >", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanOrEqualTo(String value) {
			addCriterion("creater >=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThan(String value) {
			addCriterion("creater <", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanOrEqualTo(String value) {
			addCriterion("creater <=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLike(String value) {
			addCriterion("creater like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotLike(String value) {
			addCriterion("creater not like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterIn(List<String> values) {
			addCriterion("creater in", values, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotIn(List<String> values) {
			addCriterion("creater not in", values, "creater");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreaterBetween(String value1, String value2) {
			addCriterion("creater between", value1, value2, "creater");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreaterNotBetween(String value1, String value2) {
			addCriterion("creater not between", value1, value2, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("modifier is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("modifier is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("modifier like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("modifier not like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<String> values) {
			addCriterion("modifier in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<String> values) {
			addCriterion("modifier not in", values, "modifier");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifierBetween(String value1, String value2) {
			addCriterion("modifier between", value1, value2, "modifier");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("modifier not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIsNull() {
			addCriterion("enable_status is null");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIsNotNull() {
			addCriterion("enable_status is not null");
			return (Criteria) this;
		}

		public Criteria andEnableStatusEqualTo(String value) {
			addCriterion("enable_status =", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotEqualTo(String value) {
			addCriterion("enable_status <>", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThan(String value) {
			addCriterion("enable_status >", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanOrEqualTo(String value) {
			addCriterion("enable_status >=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThan(String value) {
			addCriterion("enable_status <", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanOrEqualTo(String value) {
			addCriterion("enable_status <=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLike(String value) {
			addCriterion("enable_status like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotLike(String value) {
			addCriterion("enable_status not like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIn(List<String> values) {
			addCriterion("enable_status in", values, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotIn(List<String> values) {
			addCriterion("enable_status not in", values, "enableStatus");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andEnableStatusBetween(String value1, String value2) {
			addCriterion("enable_status between", value1, value2, "enableStatus");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andEnableStatusNotBetween(String value1, String value2) {
			addCriterion("enable_status not between", value1, value2, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderIsNull() {
			addCriterion("reorder is null");
			return (Criteria) this;
		}

		public Criteria andReorderIsNotNull() {
			addCriterion("reorder is not null");
			return (Criteria) this;
		}

		public Criteria andReorderEqualTo(String value) {
			addCriterion("reorder =", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotEqualTo(String value) {
			addCriterion("reorder <>", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThan(String value) {
			addCriterion("reorder >", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanOrEqualTo(String value) {
			addCriterion("reorder >=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLessThan(String value) {
			addCriterion("reorder <", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanOrEqualTo(String value) {
			addCriterion("reorder <=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLike(String value) {
			addCriterion("reorder like", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotLike(String value) {
			addCriterion("reorder not like", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderIn(List<String> values) {
			addCriterion("reorder in", values, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotIn(List<String> values) {
			addCriterion("reorder not in", values, "reorder");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andReorderBetween(String value1, String value2) {
			addCriterion("reorder between", value1, value2, "reorder");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andReorderNotBetween(String value1, String value2) {
			addCriterion("reorder not between", value1, value2, "reorder");
			return (Criteria) this;
		}

		protected void addCriterionIgnoreNull(String condition, Object value, String property) {
			if (value != null) {
				if (value instanceof String) {
					if (((String) value).length() > 0) {
						criteria.add(new Criterion(condition, value));
					}
				} else if (value instanceof List<?>) {
					if (((List<?>) value).size() > 0) {
						criteria.add(new Criterion(condition, value));
					}
				} else {
					criteria.add(new Criterion(condition, value));
				}
			}
		}

		public Criteria andModuleIdEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("module_id =", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_code =", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_name =", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater =", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status =", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("reorder =", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("module_id <>", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_code <>", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_name <>", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <>", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <>", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("reorder <>", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("module_id >", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("module_code >", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("module_name >", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("creater >", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status >", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("reorder >", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("module_id >=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_code >=", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_name >=", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater >=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status >=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("reorder >=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("module_id <", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("module_code <", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("module_name <", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("reorder <", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("module_id <=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_code <=", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("module_name <=", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("reorder <=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("module_id in", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("module_code in", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("module_name in", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("status in", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("creater in", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("create_time in", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("modifier in", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("modify_time in", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("enable_status in", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("remark in", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("reorder in", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("module_id not in", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleCodeNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("module_code not in", value, "moduleCode");
			return (Criteria) this;
		}

		public Criteria andModuleNameNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("module_name not in", value, "moduleName");
			return (Criteria) this;
		}

		public Criteria andStatusNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("status not in", value, "status");
			return (Criteria) this;
		}

		public Criteria andCreaterNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("creater not in", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("create_time not in", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("modifier not in", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("modify_time not in", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("enable_status not in", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andRemarkNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("remark not in", value, "remark");
			return (Criteria) this;
		}

		public Criteria andReorderNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("reorder not in", value, "reorder");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rf_picture_module
	 * @mbggenerated  Wed May 25 14:26:02 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rf_picture_module
     *
     * @mbggenerated do_not_delete_during_merge Wed May 25 10:20:38 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andModuleCodeLikeInsensitive(String value) {
            addCriterion("upper(module_code) like", value.toUpperCase(), "moduleCode");
            return this;
        }

        public Criteria andModuleNameLikeInsensitive(String value) {
            addCriterion("upper(module_name) like", value.toUpperCase(), "moduleName");
            return this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return this;
        }

        public Criteria andCreaterLikeInsensitive(String value) {
            addCriterion("upper(creater) like", value.toUpperCase(), "creater");
            return this;
        }

        public Criteria andModifierLikeInsensitive(String value) {
            addCriterion("upper(modifier) like", value.toUpperCase(), "modifier");
            return this;
        }

        public Criteria andEnableStatusLikeInsensitive(String value) {
            addCriterion("upper(enable_status) like", value.toUpperCase(), "enableStatus");
            return this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return this;
        }

        public Criteria andReorderLikeInsensitive(String value) {
            addCriterion("upper(reorder) like", value.toUpperCase(), "reorder");
            return this;
        }
    }
}