package com.redfinger.manager.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RfRankingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public RfRankingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRankingIdIsNull() {
            addCriterion("ranking_id is null");
            return (Criteria) this;
        }

        public Criteria andRankingIdIsNotNull() {
            addCriterion("ranking_id is not null");
            return (Criteria) this;
        }

        public Criteria andRankingIdEqualTo(Integer value) {
            addCriterion("ranking_id =", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdNotEqualTo(Integer value) {
            addCriterion("ranking_id <>", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdGreaterThan(Integer value) {
            addCriterion("ranking_id >", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ranking_id >=", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdLessThan(Integer value) {
            addCriterion("ranking_id <", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdLessThanOrEqualTo(Integer value) {
            addCriterion("ranking_id <=", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdIn(List<Integer> values) {
            addCriterion("ranking_id in", values, "rankingId");
            return (Criteria) this;
        }

        public Criteria andRankingIdNotIn(List<Integer> values) {
            addCriterion("ranking_id not in", values, "rankingId");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRankingIdBetween(Integer value1, Integer value2) {
            addCriterion("ranking_id between", value1, value2, "rankingId");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRankingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ranking_id not between", value1, value2, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIsNull() {
            addCriterion("ranking_type is null");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIsNotNull() {
            addCriterion("ranking_type is not null");
            return (Criteria) this;
        }

        public Criteria andRankingTypeEqualTo(String value) {
            addCriterion("ranking_type =", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeNotEqualTo(String value) {
            addCriterion("ranking_type <>", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeGreaterThan(String value) {
            addCriterion("ranking_type >", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ranking_type >=", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeLessThan(String value) {
            addCriterion("ranking_type <", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeLessThanOrEqualTo(String value) {
            addCriterion("ranking_type <=", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeLike(String value) {
            addCriterion("ranking_type like", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeNotLike(String value) {
            addCriterion("ranking_type not like", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeIn(List<String> values) {
            addCriterion("ranking_type in", values, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingTypeNotIn(List<String> values) {
            addCriterion("ranking_type not in", values, "rankingType");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRankingTypeBetween(String value1, String value2) {
            addCriterion("ranking_type between", value1, value2, "rankingType");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRankingTypeNotBetween(String value1, String value2) {
            addCriterion("ranking_type not between", value1, value2, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingIsNull() {
            addCriterion("ranking is null");
            return (Criteria) this;
        }

        public Criteria andRankingIsNotNull() {
            addCriterion("ranking is not null");
            return (Criteria) this;
        }

        public Criteria andRankingEqualTo(Integer value) {
            addCriterion("ranking =", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingNotEqualTo(Integer value) {
            addCriterion("ranking <>", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingGreaterThan(Integer value) {
            addCriterion("ranking >", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingGreaterThanOrEqualTo(Integer value) {
            addCriterion("ranking >=", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingLessThan(Integer value) {
            addCriterion("ranking <", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingLessThanOrEqualTo(Integer value) {
            addCriterion("ranking <=", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingIn(List<Integer> values) {
            addCriterion("ranking in", values, "ranking");
            return (Criteria) this;
        }

        public Criteria andRankingNotIn(List<Integer> values) {
            addCriterion("ranking not in", values, "ranking");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRankingBetween(Integer value1, Integer value2) {
            addCriterion("ranking between", value1, value2, "ranking");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRankingNotBetween(Integer value1, Integer value2) {
            addCriterion("ranking not between", value1, value2, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeIsNull() {
            addCriterion("stat_type is null");
            return (Criteria) this;
        }

        public Criteria andStatTypeIsNotNull() {
            addCriterion("stat_type is not null");
            return (Criteria) this;
        }

        public Criteria andStatTypeEqualTo(String value) {
            addCriterion("stat_type =", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeNotEqualTo(String value) {
            addCriterion("stat_type <>", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeGreaterThan(String value) {
            addCriterion("stat_type >", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeGreaterThanOrEqualTo(String value) {
            addCriterion("stat_type >=", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeLessThan(String value) {
            addCriterion("stat_type <", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeLessThanOrEqualTo(String value) {
            addCriterion("stat_type <=", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeLike(String value) {
            addCriterion("stat_type like", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeNotLike(String value) {
            addCriterion("stat_type not like", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeIn(List<String> values) {
            addCriterion("stat_type in", values, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTypeNotIn(List<String> values) {
            addCriterion("stat_type not in", values, "statType");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStatTypeBetween(String value1, String value2) {
            addCriterion("stat_type between", value1, value2, "statType");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStatTypeNotBetween(String value1, String value2) {
            addCriterion("stat_type not between", value1, value2, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeIsNull() {
            addCriterion("stat_time is null");
            return (Criteria) this;
        }

        public Criteria andStatTimeIsNotNull() {
            addCriterion("stat_time is not null");
            return (Criteria) this;
        }

        public Criteria andStatTimeEqualTo(Date value) {
            addCriterion("stat_time =", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeNotEqualTo(Date value) {
            addCriterion("stat_time <>", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeGreaterThan(Date value) {
            addCriterion("stat_time >", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("stat_time >=", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeLessThan(Date value) {
            addCriterion("stat_time <", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeLessThanOrEqualTo(Date value) {
            addCriterion("stat_time <=", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeIn(List<Date> values) {
            addCriterion("stat_time in", values, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatTimeNotIn(List<Date> values) {
            addCriterion("stat_time not in", values, "statTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStatTimeBetween(Date value1, Date value2) {
            addCriterion("stat_time between", value1, value2, "statTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStatTimeNotBetween(Date value1, Date value2) {
            addCriterion("stat_time not between", value1, value2, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusIsNull() {
            addCriterion("enable_status is null");
            return (Criteria) this;
        }

        public Criteria andEnableStatusIsNotNull() {
            addCriterion("enable_status is not null");
            return (Criteria) this;
        }

        public Criteria andEnableStatusEqualTo(String value) {
            addCriterion("enable_status =", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotEqualTo(String value) {
            addCriterion("enable_status <>", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusGreaterThan(String value) {
            addCriterion("enable_status >", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusGreaterThanOrEqualTo(String value) {
            addCriterion("enable_status >=", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLessThan(String value) {
            addCriterion("enable_status <", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLessThanOrEqualTo(String value) {
            addCriterion("enable_status <=", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLike(String value) {
            addCriterion("enable_status like", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotLike(String value) {
            addCriterion("enable_status not like", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusIn(List<String> values) {
            addCriterion("enable_status in", values, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotIn(List<String> values) {
            addCriterion("enable_status not in", values, "enableStatus");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andEnableStatusBetween(String value1, String value2) {
            addCriterion("enable_status between", value1, value2, "enableStatus");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andEnableStatusNotBetween(String value1, String value2) {
            addCriterion("enable_status not between", value1, value2, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderIsNull() {
            addCriterion("reorder is null");
            return (Criteria) this;
        }

        public Criteria andReorderIsNotNull() {
            addCriterion("reorder is not null");
            return (Criteria) this;
        }

        public Criteria andReorderEqualTo(Integer value) {
            addCriterion("reorder =", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderNotEqualTo(Integer value) {
            addCriterion("reorder <>", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderGreaterThan(Integer value) {
            addCriterion("reorder >", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderGreaterThanOrEqualTo(Integer value) {
            addCriterion("reorder >=", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderLessThan(Integer value) {
            addCriterion("reorder <", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderLessThanOrEqualTo(Integer value) {
            addCriterion("reorder <=", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderIn(List<Integer> values) {
            addCriterion("reorder in", values, "reorder");
            return (Criteria) this;
        }

        public Criteria andReorderNotIn(List<Integer> values) {
            addCriterion("reorder not in", values, "reorder");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andReorderBetween(Integer value1, Integer value2) {
            addCriterion("reorder between", value1, value2, "reorder");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andReorderNotBetween(Integer value1, Integer value2) {
            addCriterion("reorder not between", value1, value2, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        @SuppressWarnings("unused")
        private Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        protected void addCriterionIgnoreNull(String condition, Object value, String property) {
            if (value != null) {
                if (value instanceof String) {
                    if (((String) value).length() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else if (value instanceof List<?>) {
                    if(((List<?>) value).size()>0){
                        criteria.add(new Criterion(condition, value));
                    }
                } else {
                    criteria.add(new Criterion(condition, value));
                }
            }
        }

        public Criteria andRankingIdEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking_id =", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ranking_type =", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking =", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("stat_type =", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("stat_time =", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("enable_status =", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("reorder =", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking_id <>", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ranking_type <>", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking <>", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("stat_type <>", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("stat_time <>", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("enable_status <>", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("reorder <>", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking_id >", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("ranking_type >", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking >", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("stat_type >", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("stat_time >", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("enable_status >", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("reorder >", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking_id >=", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ranking_type >=", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking >=", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("stat_type >=", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("stat_time >=", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("enable_status >=", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("reorder >=", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking_id <", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("ranking_type <", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking <", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("stat_type <", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("stat_time <", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("enable_status <", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("reorder <", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking_id <=", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ranking_type <=", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("ranking <=", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("stat_type <=", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("stat_time <=", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("enable_status <=", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("reorder <=", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("ranking_id in", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("user_id in", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("ranking_type in", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("ranking in", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("num in", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("start_time in", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("end_time in", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("stat_type in", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("stat_time in", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("status in", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("enable_status in", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("creater in", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("create_time in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("modifier in", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("modify_time in", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("reorder in", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("remark in", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRankingIdNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("ranking_id not in", value, "rankingId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("user_id not in", value, "userId");
            return (Criteria) this;
        }

        public Criteria andRankingTypeNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("ranking_type not in", value, "rankingType");
            return (Criteria) this;
        }

        public Criteria andRankingNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("ranking not in", value, "ranking");
            return (Criteria) this;
        }

        public Criteria andNumNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("num not in", value, "num");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("start_time not in", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("end_time not in", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andStatTypeNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("stat_type not in", value, "statType");
            return (Criteria) this;
        }

        public Criteria andStatTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("stat_time not in", value, "statTime");
            return (Criteria) this;
        }

        public Criteria andStatusNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("status not in", value, "status");
            return (Criteria) this;
        }

        public Criteria andEnableStatusNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("enable_status not in", value, "enableStatus");
            return (Criteria) this;
        }

        public Criteria andCreaterNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("creater not in", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("create_time not in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("modifier not in", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("modify_time not in", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andReorderNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("reorder not in", value, "reorder");
            return (Criteria) this;
        }

        public Criteria andRemarkNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("remark not in", value, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rf_ranking
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 01 10:10:38 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andRankingTypeLikeInsensitive(String value) {
            addCriterion("upper(ranking_type) like", value.toUpperCase(), "rankingType");
            return this;
        }

        public Criteria andStatTypeLikeInsensitive(String value) {
            addCriterion("upper(stat_type) like", value.toUpperCase(), "statType");
            return this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return this;
        }

        public Criteria andEnableStatusLikeInsensitive(String value) {
            addCriterion("upper(enable_status) like", value.toUpperCase(), "enableStatus");
            return this;
        }

        public Criteria andCreaterLikeInsensitive(String value) {
            addCriterion("upper(creater) like", value.toUpperCase(), "creater");
            return this;
        }

        public Criteria andModifierLikeInsensitive(String value) {
            addCriterion("upper(modifier) like", value.toUpperCase(), "modifier");
            return this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rf_ranking
     *
     * @mbggenerated Wed Mar 01 10:10:38 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}