package com.redfinger.manager.common.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RfScoreLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public RfScoreLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public void setOrderByClauseIgnoreNull(String orderByClause) {
		String tmp = orderByClause.replaceAll("null", "").trim();
		if (orderByClause != null && tmp.length() > 0) {
			this.orderByClause = orderByClause;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLogIdIsNull() {
			addCriterion("log_id is null");
			return (Criteria) this;
		}

		public Criteria andLogIdIsNotNull() {
			addCriterion("log_id is not null");
			return (Criteria) this;
		}

		public Criteria andLogIdEqualTo(Integer value) {
			addCriterion("log_id =", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotEqualTo(Integer value) {
			addCriterion("log_id <>", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThan(Integer value) {
			addCriterion("log_id >", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("log_id >=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThan(Integer value) {
			addCriterion("log_id <", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThanOrEqualTo(Integer value) {
			addCriterion("log_id <=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdIn(List<Integer> values) {
			addCriterion("log_id in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotIn(List<Integer> values) {
			addCriterion("log_id not in", values, "logId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andLogIdBetween(Integer value1, Integer value2) {
			addCriterion("log_id between", value1, value2, "logId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andLogIdNotBetween(Integer value1, Integer value2) {
			addCriterion("log_id not between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("task_id is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("task_id is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(Integer value) {
			addCriterion("task_id =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(Integer value) {
			addCriterion("task_id <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(Integer value) {
			addCriterion("task_id >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("task_id >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(Integer value) {
			addCriterion("task_id <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
			addCriterion("task_id <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<Integer> values) {
			addCriterion("task_id in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<Integer> values) {
			addCriterion("task_id not in", values, "taskId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andTaskIdBetween(Integer value1, Integer value2) {
			addCriterion("task_id between", value1, value2, "taskId");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
			addCriterion("task_id not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeIsNull() {
			addCriterion("log_type is null");
			return (Criteria) this;
		}

		public Criteria andLogTypeIsNotNull() {
			addCriterion("log_type is not null");
			return (Criteria) this;
		}

		public Criteria andLogTypeEqualTo(String value) {
			addCriterion("log_type =", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotEqualTo(String value) {
			addCriterion("log_type <>", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeGreaterThan(String value) {
			addCriterion("log_type >", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeGreaterThanOrEqualTo(String value) {
			addCriterion("log_type >=", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeLessThan(String value) {
			addCriterion("log_type <", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeLessThanOrEqualTo(String value) {
			addCriterion("log_type <=", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeLike(String value) {
			addCriterion("log_type like", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotLike(String value) {
			addCriterion("log_type not like", value, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeIn(List<String> values) {
			addCriterion("log_type in", values, "logType");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotIn(List<String> values) {
			addCriterion("log_type not in", values, "logType");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andLogTypeBetween(String value1, String value2) {
			addCriterion("log_type between", value1, value2, "logType");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andLogTypeNotBetween(String value1, String value2) {
			addCriterion("log_type not between", value1, value2, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Integer value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Integer value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Integer value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Integer value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Integer value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Integer> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Integer> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andScoreBetween(Integer value1, Integer value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIsNull() {
			addCriterion("enable_status is null");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIsNotNull() {
			addCriterion("enable_status is not null");
			return (Criteria) this;
		}

		public Criteria andEnableStatusEqualTo(String value) {
			addCriterion("enable_status =", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotEqualTo(String value) {
			addCriterion("enable_status <>", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThan(String value) {
			addCriterion("enable_status >", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanOrEqualTo(String value) {
			addCriterion("enable_status >=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThan(String value) {
			addCriterion("enable_status <", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanOrEqualTo(String value) {
			addCriterion("enable_status <=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLike(String value) {
			addCriterion("enable_status like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotLike(String value) {
			addCriterion("enable_status not like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusIn(List<String> values) {
			addCriterion("enable_status in", values, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotIn(List<String> values) {
			addCriterion("enable_status not in", values, "enableStatus");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andEnableStatusBetween(String value1, String value2) {
			addCriterion("enable_status between", value1, value2,
					"enableStatus");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andEnableStatusNotBetween(String value1, String value2) {
			addCriterion("enable_status not between", value1, value2,
					"enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterIsNull() {
			addCriterion("creater is null");
			return (Criteria) this;
		}

		public Criteria andCreaterIsNotNull() {
			addCriterion("creater is not null");
			return (Criteria) this;
		}

		public Criteria andCreaterEqualTo(String value) {
			addCriterion("creater =", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotEqualTo(String value) {
			addCriterion("creater <>", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThan(String value) {
			addCriterion("creater >", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanOrEqualTo(String value) {
			addCriterion("creater >=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThan(String value) {
			addCriterion("creater <", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanOrEqualTo(String value) {
			addCriterion("creater <=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterLike(String value) {
			addCriterion("creater like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotLike(String value) {
			addCriterion("creater not like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterIn(List<String> values) {
			addCriterion("creater in", values, "creater");
			return (Criteria) this;
		}

		public Criteria andCreaterNotIn(List<String> values) {
			addCriterion("creater not in", values, "creater");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreaterBetween(String value1, String value2) {
			addCriterion("creater between", value1, value2, "creater");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreaterNotBetween(String value1, String value2) {
			addCriterion("creater not between", value1, value2, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("modifier is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("modifier is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("modifier like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("modifier not like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<String> values) {
			addCriterion("modifier in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<String> values) {
			addCriterion("modifier not in", values, "modifier");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifierBetween(String value1, String value2) {
			addCriterion("modifier between", value1, value2, "modifier");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("modifier not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2,
					"modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderIsNull() {
			addCriterion("reorder is null");
			return (Criteria) this;
		}

		public Criteria andReorderIsNotNull() {
			addCriterion("reorder is not null");
			return (Criteria) this;
		}

		public Criteria andReorderEqualTo(Integer value) {
			addCriterion("reorder =", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotEqualTo(Integer value) {
			addCriterion("reorder <>", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThan(Integer value) {
			addCriterion("reorder >", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanOrEqualTo(Integer value) {
			addCriterion("reorder >=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLessThan(Integer value) {
			addCriterion("reorder <", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanOrEqualTo(Integer value) {
			addCriterion("reorder <=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderIn(List<Integer> values) {
			addCriterion("reorder in", values, "reorder");
			return (Criteria) this;
		}

		public Criteria andReorderNotIn(List<Integer> values) {
			addCriterion("reorder not in", values, "reorder");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andReorderBetween(Integer value1, Integer value2) {
			addCriterion("reorder between", value1, value2, "reorder");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andReorderNotBetween(Integer value1, Integer value2) {
			addCriterion("reorder not between", value1, value2, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		@SuppressWarnings("unused")
		private Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		protected void addCriterionIgnoreNull(String condition, Object value,
				String property) {
			if (value != null) {
				if (value instanceof String) {
					if (condition.toLowerCase().endsWith("like")) {
						if (((String) value).replaceAll("%", "").length() > 0) {
							criteria.add(new Criterion(condition, value));
						}
					} else if (((String) value).length() > 0) {
						criteria.add(new Criterion(condition, value));
					}
				} else if (value instanceof List<?>) {
					if (((List<?>) value).size() > 0) {
						criteria.add(new Criterion(condition, value));
					}
				} else {
					criteria.add(new Criterion(condition, value));
				}
			}
		}

		public Criteria andLogIdEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id =", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type =", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status =", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater =", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder =", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id <>", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type <>", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <>", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <>", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderNotEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder <>", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id >", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type >", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status >", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("creater >", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder >", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanIgnoreNull(String value) {
			addCriterionIgnoreNull("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id >=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type >=", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusGreaterThanOrEqualToIgnoreNull(
				String value) {
			addCriterionIgnoreNull("enable_status >=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater >=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderGreaterThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder >=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id <", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type <", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder <", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id <=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type <=", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status <=", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("creater <=", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualToIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderLessThanOrEqualToIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder <=", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualToIgnoreNull(String value) {
			addCriterionIgnoreNull("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("log_id in", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("user_id in", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("task_id in", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("log_type in", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("score in", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("status in", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("enable_status in", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("creater in", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("create_time in", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("modifier in", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("modify_time in", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("reorder in", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("remark in", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("log_id not in", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("user_id not in", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("task_id not in", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("log_type not in", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("score not in", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("status not in", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("enable_status not in", value,
					"enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("creater not in", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("create_time not in", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("modifier not in", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotInIgnoreNull(List<Date> value) {
			addCriterionIgnoreNull("modify_time not in", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderNotInIgnoreNull(List<Integer> value) {
			addCriterionIgnoreNull("reorder not in", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkNotInIgnoreNull(List<String> value) {
			addCriterionIgnoreNull("remark not in", value, "remark");
			return (Criteria) this;
		}

		public Criteria andLogIdLikeIgnoreNull(Integer value) {
			addCriterionIgnoreNull("log_id like", value, "logId");
			return (Criteria) this;
		}

		public Criteria andUserIdLikeIgnoreNull(Integer value) {
			addCriterionIgnoreNull("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLikeIgnoreNull(Integer value) {
			addCriterionIgnoreNull("task_id like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andLogTypeLikeIgnoreNull(String value) {
			addCriterionIgnoreNull("log_type like", value, "logType");
			return (Criteria) this;
		}

		public Criteria andScoreLikeIgnoreNull(Integer value) {
			addCriterionIgnoreNull("score like", value, "score");
			return (Criteria) this;
		}

		public Criteria andStatusLikeIgnoreNull(String value) {
			addCriterionIgnoreNull("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andEnableStatusLikeIgnoreNull(String value) {
			addCriterionIgnoreNull("enable_status like", value, "enableStatus");
			return (Criteria) this;
		}

		public Criteria andCreaterLikeIgnoreNull(String value) {
			addCriterionIgnoreNull("creater like", value, "creater");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLikeIgnoreNull(Date value) {
			addCriterionIgnoreNull("create_time like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierLikeIgnoreNull(String value) {
			addCriterionIgnoreNull("modifier like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLikeIgnoreNull(Date value) {
			addCriterionIgnoreNull("modify_time like", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andReorderLikeIgnoreNull(Integer value) {
			addCriterionIgnoreNull("reorder like", value, "reorder");
			return (Criteria) this;
		}

		public Criteria andRemarkLikeIgnoreNull(String value) {
			addCriterionIgnoreNull("remark like", value, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rf_score_log
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rf_score_log
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 15 15:18:46 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andLogTypeLikeInsensitive(String value) {
            addCriterion("upper(log_type) like", value.toUpperCase(), "logType");
            return this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return this;
        }

        public Criteria andEnableStatusLikeInsensitive(String value) {
            addCriterion("upper(enable_status) like", value.toUpperCase(), "enableStatus");
            return this;
        }

        public Criteria andCreaterLikeInsensitive(String value) {
            addCriterion("upper(creater) like", value.toUpperCase(), "creater");
            return this;
        }

        public Criteria andModifierLikeInsensitive(String value) {
            addCriterion("upper(modifier) like", value.toUpperCase(), "modifier");
            return this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return this;
        }
    }
}