package com.redfinger.manager.common.domain;

import com.redfinger.manager.common.base.BaseDomain;
import java.io.Serializable;
import java.util.Date;

public class RfUserPadGroup extends BaseDomain implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.user_pad_group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_USER_PAD_GROUP_ID = "user_pad_group_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.user_pad_group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private Integer userPadGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.user_pad_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_USER_PAD_ID = "user_pad_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.user_pad_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private Integer userPadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_GROUP_ID = "group_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_STATUS = "status";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.creater
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_CREATER = "creater";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.creater
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private String creater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.create_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_CREATE_TIME = "create_time";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.create_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.modifier
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_MODIFIER = "modifier";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.modifier
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.modify_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_MODIFY_TIME = "modify_time";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.modify_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.reorder
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_REORDER = "reorder";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.reorder
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private Integer reorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.remark
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_REMARK = "remark";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.remark
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.enable_status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public static final String FD_ENABLE_STATUS = "enable_status";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rf_user_pad_group.enable_status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private String enableStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rf_user_pad_group
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.user_pad_group_id
	 * @return  the value of rf_user_pad_group.user_pad_group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public Integer getUserPadGroupId() {
		return userPadGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.user_pad_group_id
	 * @param userPadGroupId  the value for rf_user_pad_group.user_pad_group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setUserPadGroupId(Integer userPadGroupId) {
		this.userPadGroupId = userPadGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.user_pad_id
	 * @return  the value of rf_user_pad_group.user_pad_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public Integer getUserPadId() {
		return userPadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.user_pad_id
	 * @param userPadId  the value for rf_user_pad_group.user_pad_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setUserPadId(Integer userPadId) {
		this.userPadId = userPadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.group_id
	 * @return  the value of rf_user_pad_group.group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.group_id
	 * @param groupId  the value for rf_user_pad_group.group_id
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.status
	 * @return  the value of rf_user_pad_group.status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.status
	 * @param status  the value for rf_user_pad_group.status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.creater
	 * @return  the value of rf_user_pad_group.creater
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.creater
	 * @param creater  the value for rf_user_pad_group.creater
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setCreater(String creater) {
		this.creater = creater == null ? null : creater.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.create_time
	 * @return  the value of rf_user_pad_group.create_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.create_time
	 * @param createTime  the value for rf_user_pad_group.create_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.modifier
	 * @return  the value of rf_user_pad_group.modifier
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.modifier
	 * @param modifier  the value for rf_user_pad_group.modifier
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier == null ? null : modifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.modify_time
	 * @return  the value of rf_user_pad_group.modify_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.modify_time
	 * @param modifyTime  the value for rf_user_pad_group.modify_time
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.reorder
	 * @return  the value of rf_user_pad_group.reorder
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public Integer getReorder() {
		return reorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.reorder
	 * @param reorder  the value for rf_user_pad_group.reorder
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setReorder(Integer reorder) {
		this.reorder = reorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.remark
	 * @return  the value of rf_user_pad_group.remark
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.remark
	 * @param remark  the value for rf_user_pad_group.remark
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rf_user_pad_group.enable_status
	 * @return  the value of rf_user_pad_group.enable_status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public String getEnableStatus() {
		return enableStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rf_user_pad_group.enable_status
	 * @param enableStatus  the value for rf_user_pad_group.enable_status
	 * @mbggenerated  Sun Dec 10 15:34:23 CST 2017
	 */
	public void setEnableStatus(String enableStatus) {
		this.enableStatus = enableStatus == null ? null : enableStatus.trim();
	}
}