package com.redfinger.manager.common.domain;

import com.redfinger.manager.common.base.BaseDomain;
import java.io.Serializable;
import java.util.Date;

public class ViewSurveyLog extends BaseDomain implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.log_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_LOG_ID = "log_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.log_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Integer logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_USER_ID = "user_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.survey_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_SURVEY_ID = "survey_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.survey_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Integer surveyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.problem_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_PROBLEM_ID = "problem_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.problem_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Integer problemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.answer_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_ANSWER_ID = "answer_id";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.answer_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Integer answerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.answer_content
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_ANSWER_CONTENT = "answer_content";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.answer_content
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String answerContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.enable_status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_ENABLE_STATUS = "enable_status";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.enable_status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String enableStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_STATUS = "status";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.creater
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_CREATER = "creater";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.creater
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String creater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.create_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_CREATE_TIME = "create_time";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.create_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.modifier
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_MODIFIER = "modifier";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.modifier
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String modifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.modify_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_MODIFY_TIME = "modify_time";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.modify_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.reorder
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_REORDER = "reorder";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.reorder
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private Integer reorder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.remark
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_REMARK = "remark";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.remark
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_name_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_USER_NAME_T2 = "user_name_t2";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_name_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String userNameT2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_mobile_phone_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_USER_MOBILE_PHONE_T2 = "user_mobile_phone_t2";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_mobile_phone_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String userMobilePhoneT2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_email_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_USER_EMAIL_T2 = "user_email_t2";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.user_email_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String userEmailT2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.survey_name_t3
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_SURVEY_NAME_T3 = "survey_name_t3";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.survey_name_t3
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String surveyNameT3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.problem_content_t4
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_PROBLEM_CONTENT_T4 = "problem_content_t4";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.problem_content_t4
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String problemContentT4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.answer_content_t5
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public static final String FD_ANSWER_CONTENT_T5 = "answer_content_t5";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column view_survey_log.answer_content_t5
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private String answerContentT5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table view_survey_log
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.log_id
	 * @return  the value of view_survey_log.log_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Integer getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.log_id
	 * @param logId  the value for view_survey_log.log_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.user_id
	 * @return  the value of view_survey_log.user_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.user_id
	 * @param userId  the value for view_survey_log.user_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.survey_id
	 * @return  the value of view_survey_log.survey_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Integer getSurveyId() {
		return surveyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.survey_id
	 * @param surveyId  the value for view_survey_log.survey_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setSurveyId(Integer surveyId) {
		this.surveyId = surveyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.problem_id
	 * @return  the value of view_survey_log.problem_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Integer getProblemId() {
		return problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.problem_id
	 * @param problemId  the value for view_survey_log.problem_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setProblemId(Integer problemId) {
		this.problemId = problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.answer_id
	 * @return  the value of view_survey_log.answer_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Integer getAnswerId() {
		return answerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.answer_id
	 * @param answerId  the value for view_survey_log.answer_id
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.answer_content
	 * @return  the value of view_survey_log.answer_content
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getAnswerContent() {
		return answerContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.answer_content
	 * @param answerContent  the value for view_survey_log.answer_content
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent == null ? null : answerContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.enable_status
	 * @return  the value of view_survey_log.enable_status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getEnableStatus() {
		return enableStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.enable_status
	 * @param enableStatus  the value for view_survey_log.enable_status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setEnableStatus(String enableStatus) {
		this.enableStatus = enableStatus == null ? null : enableStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.status
	 * @return  the value of view_survey_log.status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.status
	 * @param status  the value for view_survey_log.status
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.creater
	 * @return  the value of view_survey_log.creater
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.creater
	 * @param creater  the value for view_survey_log.creater
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setCreater(String creater) {
		this.creater = creater == null ? null : creater.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.create_time
	 * @return  the value of view_survey_log.create_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.create_time
	 * @param createTime  the value for view_survey_log.create_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.modifier
	 * @return  the value of view_survey_log.modifier
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getModifier() {
		return modifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.modifier
	 * @param modifier  the value for view_survey_log.modifier
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier == null ? null : modifier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.modify_time
	 * @return  the value of view_survey_log.modify_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.modify_time
	 * @param modifyTime  the value for view_survey_log.modify_time
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.reorder
	 * @return  the value of view_survey_log.reorder
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public Integer getReorder() {
		return reorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.reorder
	 * @param reorder  the value for view_survey_log.reorder
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setReorder(Integer reorder) {
		this.reorder = reorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.remark
	 * @return  the value of view_survey_log.remark
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.remark
	 * @param remark  the value for view_survey_log.remark
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.user_name_t2
	 * @return  the value of view_survey_log.user_name_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getUserNameT2() {
		return userNameT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.user_name_t2
	 * @param userNameT2  the value for view_survey_log.user_name_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setUserNameT2(String userNameT2) {
		this.userNameT2 = userNameT2 == null ? null : userNameT2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.user_mobile_phone_t2
	 * @return  the value of view_survey_log.user_mobile_phone_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getUserMobilePhoneT2() {
		return userMobilePhoneT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.user_mobile_phone_t2
	 * @param userMobilePhoneT2  the value for view_survey_log.user_mobile_phone_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setUserMobilePhoneT2(String userMobilePhoneT2) {
		this.userMobilePhoneT2 = userMobilePhoneT2 == null ? null : userMobilePhoneT2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.user_email_t2
	 * @return  the value of view_survey_log.user_email_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getUserEmailT2() {
		return userEmailT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.user_email_t2
	 * @param userEmailT2  the value for view_survey_log.user_email_t2
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setUserEmailT2(String userEmailT2) {
		this.userEmailT2 = userEmailT2 == null ? null : userEmailT2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.survey_name_t3
	 * @return  the value of view_survey_log.survey_name_t3
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getSurveyNameT3() {
		return surveyNameT3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.survey_name_t3
	 * @param surveyNameT3  the value for view_survey_log.survey_name_t3
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setSurveyNameT3(String surveyNameT3) {
		this.surveyNameT3 = surveyNameT3 == null ? null : surveyNameT3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.problem_content_t4
	 * @return  the value of view_survey_log.problem_content_t4
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getProblemContentT4() {
		return problemContentT4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.problem_content_t4
	 * @param problemContentT4  the value for view_survey_log.problem_content_t4
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setProblemContentT4(String problemContentT4) {
		this.problemContentT4 = problemContentT4 == null ? null : problemContentT4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column view_survey_log.answer_content_t5
	 * @return  the value of view_survey_log.answer_content_t5
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public String getAnswerContentT5() {
		return answerContentT5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column view_survey_log.answer_content_t5
	 * @param answerContentT5  the value for view_survey_log.answer_content_t5
	 * @mbggenerated  Thu Mar 31 19:54:20 CST 2016
	 */
	public void setAnswerContentT5(String answerContentT5) {
		this.answerContentT5 = answerContentT5 == null ? null : answerContentT5.trim();
	}
}