package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.AgentGameDetail;
import com.redfinger.manager.common.domain.AgentGameDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentGameDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int countByExample(AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int deleteByExample(AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int insert(AgentGameDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int insertSelective(AgentGameDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	List<AgentGameDetail> selectByExample(AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	AgentGameDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int updateByExampleSelective(@Param("record") AgentGameDetail record,
			@Param("example") AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int updateByExample(@Param("record") AgentGameDetail record, @Param("example") AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int updateByPrimaryKeySelective(AgentGameDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int updateByPrimaryKey(AgentGameDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	AgentGameDetail selectOneByExample(AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	List<AgentGameDetail> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	AgentGameDetail selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int insertBatch(List<AgentGameDetail> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") AgentGameDetail record,
			@Param("example") AgentGameDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(AgentGameDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_game_detail
	 * @mbggenerated  Wed Mar 09 15:04:57 CST 2016
	 */
	AgentGameDetail selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Integer id);
}