package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.HelpFeedback;
import com.redfinger.manager.common.domain.HelpFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelpFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int countByExample(HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int deleteByExample(HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int deleteByPrimaryKey(Integer feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int insert(HelpFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int insertSelective(HelpFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    List<HelpFeedback> selectByExample(HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    HelpFeedback selectByPrimaryKey(Integer feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") HelpFeedback record, @Param("example") HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int updateByExample(@Param("record") HelpFeedback record, @Param("example") HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int updateByPrimaryKeySelective(HelpFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int updateByPrimaryKey(HelpFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    HelpFeedback selectOneByExample(HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    List<HelpFeedback> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    HelpFeedback selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int insertBatch(List<HelpFeedback> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int updateByExampleSelectiveSync(@Param("record") HelpFeedback record, @Param("example") HelpFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    int updateByPrimaryKeySelectiveSync(HelpFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_feedback
     *
     * @mbggenerated Thu May 26 09:08:23 CST 2016
     */
    HelpFeedback selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("feedbackId") Integer feedbackId);
}