package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.LogMarketCatch;
import com.redfinger.manager.common.domain.LogMarketCatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogMarketCatchMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int countByExample(LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByExample(LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insert(LogMarketCatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertSelective(LogMarketCatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<LogMarketCatch> selectByExample(LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	LogMarketCatch selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExampleSelective(@Param("record") LogMarketCatch record, @Param("example") LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExample(@Param("record") LogMarketCatch record, @Param("example") LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelective(LogMarketCatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKey(LogMarketCatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	LogMarketCatch selectOneByExample(LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<LogMarketCatch> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	LogMarketCatch selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") LogMarketCatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertBatch(List<LogMarketCatch> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelectiveSync(LogMarketCatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table log_market_catch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	LogMarketCatch selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Integer id);
}