package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.PushInfoBatch;
import com.redfinger.manager.common.domain.PushInfoBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushInfoBatchMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int countByExample(PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByExample(PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insert(PushInfoBatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertSelective(PushInfoBatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<PushInfoBatch> selectByExample(PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	PushInfoBatch selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExampleSelective(@Param("record") PushInfoBatch record, @Param("example") PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExample(@Param("record") PushInfoBatch record, @Param("example") PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelective(PushInfoBatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKey(PushInfoBatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	PushInfoBatch selectOneByExample(PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<PushInfoBatch> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	PushInfoBatch selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") PushInfoBatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertBatch(List<PushInfoBatch> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelectiveSync(PushInfoBatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table push_info_batch
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	PushInfoBatch selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Integer id);
}