package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfCouponLog;
import com.redfinger.manager.common.domain.RfCouponLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfCouponLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int countByExample(RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int deleteByExample(RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int deleteByPrimaryKey(Integer couponLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int insert(RfCouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int insertSelective(RfCouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    List<RfCouponLog> selectByExample(RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfCouponLog selectByPrimaryKey(Integer couponLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") RfCouponLog record, @Param("example") RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByExample(@Param("record") RfCouponLog record, @Param("example") RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByPrimaryKeySelective(RfCouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByPrimaryKey(RfCouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfCouponLog selectOneByExample(RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    List<RfCouponLog> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfCouponLog selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int insertBatch(List<RfCouponLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByExampleSelectiveSync(@Param("record") RfCouponLog record, @Param("example") RfCouponLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByPrimaryKeySelectiveSync(RfCouponLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_coupon_log
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfCouponLog selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("couponLogId") Integer couponLogId);
}