package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfDevice;
import com.redfinger.manager.common.domain.RfDeviceExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RfDeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int countByExample(RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int deleteByExample(RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int deleteByPrimaryKey(Integer deviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int insert(RfDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int insertSelective(RfDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	List<RfDevice> selectByExample(RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	RfDevice selectByPrimaryKey(Integer deviceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RfDevice record, @Param("example") RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int updateByExample(@Param("record") RfDevice record, @Param("example") RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int updateByPrimaryKeySelective(RfDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int updateByPrimaryKey(RfDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	RfDevice selectOneByExample(RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	List<RfDevice> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	RfDevice selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int insertBatch(List<RfDevice> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") RfDevice record, @Param("example") RfDeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(RfDevice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_device
	 * @mbggenerated  Fri Dec 16 15:43:28 CST 2016
	 */
	RfDevice selectByPrimaryKeyShowField(@Param("showField") List<String> showField,
			@Param("deviceId") Integer deviceId);
}