package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfGoodsType;
import com.redfinger.manager.common.domain.RfGoodsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfGoodsTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int countByExample(RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int deleteByExample(RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int deleteByPrimaryKey(Integer typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int insert(RfGoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int insertSelective(RfGoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	List<RfGoodsType> selectByExample(RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	RfGoodsType selectByPrimaryKey(Integer typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RfGoodsType record, @Param("example") RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int updateByExample(@Param("record") RfGoodsType record, @Param("example") RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int updateByPrimaryKeySelective(RfGoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int updateByPrimaryKey(RfGoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	RfGoodsType selectOneByExample(RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	List<RfGoodsType> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	RfGoodsType selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int insertBatch(List<RfGoodsType> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") RfGoodsType record, @Param("example") RfGoodsTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(RfGoodsType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_goods_type
	 * @mbggenerated  Fri Dec 30 10:40:10 CST 2016
	 */
	RfGoodsType selectByPrimaryKeyShowField(@Param("showField") List<String> showField,
			@Param("typeId") Integer typeId);
}