package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfHotSearch;
import com.redfinger.manager.common.domain.RfHotSearchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfHotSearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int countByExample(RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int deleteByExample(RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int insert(RfHotSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int insertSelective(RfHotSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    List<RfHotSearch> selectByExample(RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    RfHotSearch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") RfHotSearch record, @Param("example") RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int updateByExample(@Param("record") RfHotSearch record, @Param("example") RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int updateByPrimaryKeySelective(RfHotSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int updateByPrimaryKey(RfHotSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    RfHotSearch selectOneByExample(RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    List<RfHotSearch> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    RfHotSearch selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int insertBatch(List<RfHotSearch> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int updateByExampleSelectiveSync(@Param("record") RfHotSearch record, @Param("example") RfHotSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    int updateByPrimaryKeySelectiveSync(RfHotSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_hot_search
     *
     * @mbggenerated Thu Feb 16 16:36:58 CST 2017
     */
    RfHotSearch selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Integer id);
}