package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfInformation;
import com.redfinger.manager.common.domain.RfInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int countByExample(RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int deleteByExample(RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int insert(RfInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int insertSelective(RfInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    List<RfInformation> selectByExample(RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    RfInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") RfInformation record, @Param("example") RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int updateByExample(@Param("record") RfInformation record, @Param("example") RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int updateByPrimaryKeySelective(RfInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int updateByPrimaryKey(RfInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    RfInformation selectOneByExample(RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    List<RfInformation> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    RfInformation selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int insertBatch(List<RfInformation> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int updateByExampleSelectiveSync(@Param("record") RfInformation record, @Param("example") RfInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    int updateByPrimaryKeySelectiveSync(RfInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_information
     *
     * @mbggenerated Wed Oct 12 14:25:08 CST 2016
     */
    RfInformation selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Integer id);
}