package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfOrderData;
import com.redfinger.manager.common.domain.RfOrderDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfOrderDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int countByExample(RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int deleteByExample(RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int deleteByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int insert(RfOrderData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int insertSelective(RfOrderData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    List<RfOrderData> selectByExample(RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfOrderData selectByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") RfOrderData record, @Param("example") RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByExample(@Param("record") RfOrderData record, @Param("example") RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByPrimaryKeySelective(RfOrderData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByPrimaryKey(RfOrderData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfOrderData selectOneByExample(RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    List<RfOrderData> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfOrderData selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int insertBatch(List<RfOrderData> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByExampleSelectiveSync(@Param("record") RfOrderData record, @Param("example") RfOrderDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    int updateByPrimaryKeySelectiveSync(RfOrderData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_order_data
     *
     * @mbggenerated Tue Oct 25 15:00:08 CST 2016
     */
    RfOrderData selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("dataId") Integer dataId);
}