package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfPadGrantLog;
import com.redfinger.manager.common.domain.RfPadGrantLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfPadGrantLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int countByExample(RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int deleteByExample(RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int deleteByPrimaryKey(Integer grantLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int insert(RfPadGrantLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int insertSelective(RfPadGrantLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    List<RfPadGrantLog> selectByExample(RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    RfPadGrantLog selectByPrimaryKey(Integer grantLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") RfPadGrantLog record, @Param("example") RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int updateByExample(@Param("record") RfPadGrantLog record, @Param("example") RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int updateByPrimaryKeySelective(RfPadGrantLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int updateByPrimaryKey(RfPadGrantLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    RfPadGrantLog selectOneByExample(RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    List<RfPadGrantLog> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    RfPadGrantLog selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int insertBatch(List<RfPadGrantLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int updateByExampleSelectiveSync(@Param("record") RfPadGrantLog record, @Param("example") RfPadGrantLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    int updateByPrimaryKeySelectiveSync(RfPadGrantLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_grant_log
     *
     * @mbggenerated Tue Jun 21 15:34:38 CST 2016
     */
    RfPadGrantLog selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("grantLogId") Integer grantLogId);
}