package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfPadRbcStandard;
import com.redfinger.manager.common.domain.RfPadRbcStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfPadRbcStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int countByExample(RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int deleteByExample(RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int deleteByPrimaryKey(Integer standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int insert(RfPadRbcStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int insertSelective(RfPadRbcStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    List<RfPadRbcStandard> selectByExample(RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    RfPadRbcStandard selectByPrimaryKey(Integer standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") RfPadRbcStandard record, @Param("example") RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int updateByExample(@Param("record") RfPadRbcStandard record, @Param("example") RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int updateByPrimaryKeySelective(RfPadRbcStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int updateByPrimaryKey(RfPadRbcStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    RfPadRbcStandard selectOneByExample(RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    List<RfPadRbcStandard> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    RfPadRbcStandard selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int insertBatch(List<RfPadRbcStandard> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int updateByExampleSelectiveSync(@Param("record") RfPadRbcStandard record, @Param("example") RfPadRbcStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    int updateByPrimaryKeySelectiveSync(RfPadRbcStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_pad_rbc_standard
     *
     * @mbggenerated Fri May 12 13:56:05 CST 2017
     */
    RfPadRbcStandard selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("standardId") Integer standardId);
}