package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfPayTradeLog;
import com.redfinger.manager.common.domain.RfPayTradeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfPayTradeLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int countByExample(RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int deleteByExample(RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int deleteByPrimaryKey(Integer tradeLogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int insert(RfPayTradeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int insertSelective(RfPayTradeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	List<RfPayTradeLog> selectByExample(RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	RfPayTradeLog selectByPrimaryKey(Integer tradeLogId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RfPayTradeLog record, @Param("example") RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int updateByExample(@Param("record") RfPayTradeLog record, @Param("example") RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int updateByPrimaryKeySelective(RfPayTradeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int updateByPrimaryKey(RfPayTradeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	RfPayTradeLog selectOneByExample(RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	List<RfPayTradeLog> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	RfPayTradeLog selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int insertBatch(List<RfPayTradeLog> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") RfPayTradeLog record, @Param("example") RfPayTradeLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(RfPayTradeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_pay_trade_log
	 * @mbggenerated  Thu Mar 24 11:18:31 CST 2016
	 */
	RfPayTradeLog selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("tradeLogId") Integer tradeLogId);
	
	/**
	 * 
	 * 根据条件统计金额
	 * @param example
	 * @return Integer
	 */
	Long tradeMoneySumByExample(RfPayTradeLogExample example);

}