package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfProblemAnswer;
import com.redfinger.manager.common.domain.RfProblemAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfProblemAnswerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int countByExample(RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByExample(RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByPrimaryKey(Integer answerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insert(RfProblemAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertSelective(RfProblemAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<RfProblemAnswer> selectByExample(RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfProblemAnswer selectByPrimaryKey(Integer answerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExampleSelective(@Param("record") RfProblemAnswer record, @Param("example") RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExample(@Param("record") RfProblemAnswer record, @Param("example") RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelective(RfProblemAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKey(RfProblemAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfProblemAnswer selectOneByExample(RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<RfProblemAnswer> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfProblemAnswer selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfProblemAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertBatch(List<RfProblemAnswer> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelectiveSync(RfProblemAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_problem_answer
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfProblemAnswer selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("answerId") Integer answerId);
}