package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfScoreGrade;
import com.redfinger.manager.common.domain.RfScoreGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfScoreGradeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int countByExample(RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int deleteByExample(RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer gradeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int insert(RfScoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int insertSelective(RfScoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	List<RfScoreGrade> selectByExample(RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	RfScoreGrade selectByPrimaryKey(Integer gradeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RfScoreGrade record,
			@Param("example") RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int updateByExample(@Param("record") RfScoreGrade record,
			@Param("example") RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int updateByPrimaryKeySelective(RfScoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int updateByPrimaryKey(RfScoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	RfScoreGrade selectOneByExample(RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	List<RfScoreGrade> selectByExampleShowField(
			@Param("showField") List<String> showField,
			@Param("example") RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	RfScoreGrade selectOneByExampleShowField(
			@Param("showField") List<String> showField,
			@Param("example") RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int insertBatch(List<RfScoreGrade> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") RfScoreGrade record,
			@Param("example") RfScoreGradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(RfScoreGrade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_score_grade
	 * @mbggenerated  Fri Jul 15 15:23:53 CST 2016
	 */
	RfScoreGrade selectByPrimaryKeyShowField(
			@Param("showField") List<String> showField,
			@Param("gradeId") Integer gradeId);
}