package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfTaskRecord;
import com.redfinger.manager.common.domain.RfTaskRecordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RfTaskRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int countByExample(RfTaskRecordExample example);
	
	int selectCountByExample(Map<String,Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int deleteByExample(RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int deleteByPrimaryKey(Integer recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int insert(RfTaskRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int insertSelective(RfTaskRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	List<RfTaskRecord> selectByExample(RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	RfTaskRecord selectByPrimaryKey(Integer recordId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RfTaskRecord record,
			@Param("example") RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int updateByExample(@Param("record") RfTaskRecord record,
			@Param("example") RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int updateByPrimaryKeySelective(RfTaskRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int updateByPrimaryKey(RfTaskRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	RfTaskRecord selectOneByExample(RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	List<RfTaskRecord> selectByExampleShowField(
			@Param("showField") List<String> showField,
			@Param("example") RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	RfTaskRecord selectOneByExampleShowField(
			@Param("showField") List<String> showField,
			@Param("example") RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int insertBatch(List<RfTaskRecord> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") RfTaskRecord record,
			@Param("example") RfTaskRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(RfTaskRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_task_record
	 * @mbggenerated  Fri Sep 09 17:00:17 CST 2016
	 */
	RfTaskRecord selectByPrimaryKeyShowField(
			@Param("showField") List<String> showField,
			@Param("recordId") Integer recordId);
}