package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfTreasurePeriod;
import com.redfinger.manager.common.domain.RfTreasurePeriodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfTreasurePeriodMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int countByExample(RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int deleteByExample(RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int deleteByPrimaryKey(Integer periodId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int insert(RfTreasurePeriod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int insertSelective(RfTreasurePeriod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	List<RfTreasurePeriod> selectByExample(RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	RfTreasurePeriod selectByPrimaryKey(Integer periodId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int updateByExampleSelective(@Param("record") RfTreasurePeriod record,
			@Param("example") RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int updateByExample(@Param("record") RfTreasurePeriod record, @Param("example") RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int updateByPrimaryKeySelective(RfTreasurePeriod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int updateByPrimaryKey(RfTreasurePeriod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	RfTreasurePeriod selectOneByExample(RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	List<RfTreasurePeriod> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	RfTreasurePeriod selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int insertBatch(List<RfTreasurePeriod> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int updateByExampleSelectiveSync(@Param("record") RfTreasurePeriod record,
			@Param("example") RfTreasurePeriodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	int updateByPrimaryKeySelectiveSync(RfTreasurePeriod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_treasure_period
	 * @mbggenerated  Wed Mar 15 19:26:50 CST 2017
	 */
	RfTreasurePeriod selectByPrimaryKeyShowField(@Param("showField") List<String> showField,
			@Param("periodId") Integer periodId);
}