package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfUserPad;
import com.redfinger.manager.common.domain.RfUserPadExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RfUserPadMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int countByExample(RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int deleteByExample(RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int deleteByPrimaryKey(Integer userPadId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int insert(RfUserPad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int insertSelective(RfUserPad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	List<RfUserPad> selectByExample(RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	RfUserPad selectByPrimaryKey(Integer userPadId);
	
	RfUserPad selectByPadCode(Map<String,Object> map);
	
	List<RfUserPad> selectByIdc(Map<String,Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RfUserPad record, @Param("example") RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int updateByExample(@Param("record") RfUserPad record, @Param("example") RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int updateByPrimaryKeySelective(RfUserPad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int updateByPrimaryKey(RfUserPad record);
	
	int updateExpireTimeByDays(Map<String,Object> map);
	int updateExpireTimeByHours(Map<String,Object> map);
	int updateExpireTimeByMinutes(Map<String,Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	RfUserPad selectOneByExample(RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	List<RfUserPad> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	RfUserPad selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int insertBatch(List<RfUserPad> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int updateByExampleSelectiveSync(@Param("record") RfUserPad record, @Param("example") RfUserPadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	int updateByPrimaryKeySelectiveSync(RfUserPad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_user_pad
	 * @mbggenerated  Mon May 16 09:41:18 CST 2016
	 */
	RfUserPad selectByPrimaryKeyShowField(@Param("showField") List<String> showField,
			@Param("userPadId") Integer userPadId);
}