package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfVersion;
import com.redfinger.manager.common.domain.RfVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfVersionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int countByExample(RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByExample(RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int deleteByPrimaryKey(Integer versionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insert(RfVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertSelective(RfVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<RfVersion> selectByExample(RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfVersion selectByPrimaryKey(Integer versionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExampleSelective(@Param("record") RfVersion record, @Param("example") RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByExample(@Param("record") RfVersion record, @Param("example") RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelective(RfVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKey(RfVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfVersion selectOneByExample(RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	List<RfVersion> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfVersion selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int insertBatch(List<RfVersion> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	int updateByPrimaryKeySelectiveSync(RfVersion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_version
	 * @mbggenerated  Mon Dec 21 11:12:38 CST 2015
	 */
	RfVersion selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("versionId") Integer versionId);
}