package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfWalletAccount;
import com.redfinger.manager.common.domain.RfWalletAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfWalletAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int countByExample(RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int deleteByExample(RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int deleteByPrimaryKey(Integer accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int insert(RfWalletAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int insertSelective(RfWalletAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	List<RfWalletAccount> selectByExample(RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	RfWalletAccount selectByPrimaryKey(Integer accountId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int updateByExampleSelective(@Param("record") RfWalletAccount record,
			@Param("example") RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int updateByExample(@Param("record") RfWalletAccount record, @Param("example") RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int updateByPrimaryKeySelective(RfWalletAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int updateByPrimaryKey(RfWalletAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	RfWalletAccount selectOneByExample(RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	List<RfWalletAccount> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	RfWalletAccount selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int insertBatch(List<RfWalletAccount> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int updateByExampleSelectiveSync(@Param("record") RfWalletAccount record,
			@Param("example") RfWalletAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	int updateByPrimaryKeySelectiveSync(RfWalletAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rf_wallet_account
	 * @mbggenerated  Wed Mar 22 11:02:30 CST 2017
	 */
	RfWalletAccount selectByPrimaryKeyShowField(@Param("showField") List<String> showField,
			@Param("accountId") Integer accountId);
}