package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.RfWechartTemplate;
import com.redfinger.manager.common.domain.RfWechartTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RfWechartTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int countByExample(RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int deleteByExample(RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int insert(RfWechartTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int insertSelective(RfWechartTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    List<RfWechartTemplate> selectByExample(RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    RfWechartTemplate selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") RfWechartTemplate record, @Param("example") RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int updateByExample(@Param("record") RfWechartTemplate record, @Param("example") RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int updateByPrimaryKeySelective(RfWechartTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int updateByPrimaryKey(RfWechartTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    RfWechartTemplate selectOneByExample(RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    List<RfWechartTemplate> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    RfWechartTemplate selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int insertBatch(List<RfWechartTemplate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int updateByExampleSelectiveSync(@Param("record") RfWechartTemplate record, @Param("example") RfWechartTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    int updateByPrimaryKeySelectiveSync(RfWechartTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rf_wechart_template
     *
     * @mbggenerated Mon Mar 27 17:38:28 CST 2017
     */
    RfWechartTemplate selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("templateId") Integer templateId);
}