package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.TkBatchTask;
import com.redfinger.manager.common.domain.TkBatchTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TkBatchTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int countByExample(TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int deleteByExample(TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int deleteByPrimaryKey(Integer batchId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int insert(TkBatchTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int insertSelective(TkBatchTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	List<TkBatchTask> selectByExample(TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	TkBatchTask selectByPrimaryKey(Integer batchId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TkBatchTask record, @Param("example") TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int updateByExample(@Param("record") TkBatchTask record, @Param("example") TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int updateByPrimaryKeySelective(TkBatchTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int updateByPrimaryKey(TkBatchTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	TkBatchTask selectOneByExample(TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	List<TkBatchTask> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	TkBatchTask selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int insertBatch(List<TkBatchTask> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int updateByExampleSelectiveSync(@Param("record") TkBatchTask record, @Param("example") TkBatchTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	int updateByPrimaryKeySelectiveSync(TkBatchTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_batch_task
	 * @mbggenerated  Wed May 17 18:20:56 CST 2017
	 */
	TkBatchTask selectByPrimaryKeyShowField(@Param("showField") List<String> showField,
			@Param("batchId") Integer batchId);
}