package com.redfinger.manager.common.mapper;

import com.redfinger.manager.common.domain.TkTask;
import com.redfinger.manager.common.domain.TkTaskExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TkTaskMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int countByExample(TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int deleteByExample(TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int deleteByPrimaryKey(Integer taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int insert(TkTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int insertSelective(TkTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	List<TkTask> selectByExample(TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	TkTask selectByPrimaryKey(Integer taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TkTask record, @Param("example") TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int updateByExample(@Param("record") TkTask record, @Param("example") TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int updateByPrimaryKeySelective(TkTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int updateByPrimaryKey(TkTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	TkTask selectOneByExample(TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	List<TkTask> selectByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	TkTask selectOneByExampleShowField(@Param("showField") List<String> showField,
			@Param("example") TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int insertBatch(List<TkTask> list);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int updateByExampleSelectiveSync(@Param("record") TkTask record, @Param("example") TkTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	int updateByPrimaryKeySelectiveSync(TkTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tk_task
	 * @mbggenerated  Fri Feb 17 15:22:15 CST 2017
	 */
	TkTask selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("taskId") Integer taskId);

	public int selectCountByTaskCode(Map<String,Object> params);
}